apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: monitoring
  name: demo-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-nginx
  template:
    metadata:
      labels:
        app: demo-nginx
    spec:
      containers:
      - name: demo-nginx
        image: otel/demo:latest-quote
        env:
          - name: QUOTE_PORT
            value: "8090"
          - name: OTEL_PHP_AUTOLOAD_ENABLED
            value: "true"
          - name: OTEL_SERVICE_NAME
            value: demo-nginx
          - name: OTEL_RESOURCE_ATTRIBUTES
            value: service.namespace=monitoring,app=demo-nginx
          - name: OTEL_TRACES_EXPORTER
            value: otlp
          - name: OTEL_METRICS_EXPORTER
            value: otlp
          - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
            value: http://otel-metrics.monitoring:4318/v1/traces
          - name: OTEL_EXPORTER_OTLP_TRACES_PROTOCOL
            value: http/protobuf
          - name: OTEL_EXPORTER_OTLP_METRICS_ENDPOINT
            value: http://otel-metrics.monitoring:4318/v1/metrics
          - name: OTEL_EXPORTER_OTLP_METRICS_PROTOCOL
            value: http/protobuf
        ports:
        - containerPort: 8090
          name: http
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: demo-nginx
spec:
  selector:
    app: demo-nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8090
